### ISSUE TITLE
[Bug] [Scrcpy] Scrcpy no longer works

### ISSUE THREAD

**Issue by CorruptionVR** [tango-adb/old-demo#1]
Whenever I try to use scrcpy, it just stops right after I start it

Steps
 - Connect device
 - Start Scrcpy
 - Scrcpy stops

there are no console errors, so I don't know whats going on.

**Comment by yume-chan** [comment]
I think the obsolete version of Scrcpy in old demo won't work on Android 14. It needs to be updated.

**Comment by dev-rvk** [comment]
> I think the obsolete version of Scrcpy in old demo won't work on Android 14. It needs to be updated.

Any guide or reference on how to update? It seems to be using `@yume-chan/scrcpy` so ideally the latest version should be fetched from the registry.
I have checked, Scrcpy is working with the web socket connection.

**Comment by yume-chan** [comment]
https://docs.tangoapp.dev/scrcpy/prepare-server/#use-yume-chanfetch-scrcpy-server

Only updating the server binary should be enough.

**Comment by dev-rvk** [comment]
> https://docs.tangoapp.dev/scrcpy/prepare-server/#use-yume-chanfetch-scrcpy-server
> 
> Only updating the server binary should be enough.

<img width="1470" alt="Screenshot 2024-07-25 at 4 36 16 PM" src="https://github.com/user-attachments/assets/5354af33-d32a-468f-98c0-7de4f46926fb">

The Issue seems to be more than updating Scrcpy, The device is unable to connect.
