### ISSUE TITLE
是否可以支持非https下使用

### ISSUE THREAD

**Issue by Boris-code** [tango-adb/old-demo#2]
目前部署静态页面，使用localhost可以使用，但使用本机ip地址不可以。是否是因为非https原因呢？可以支持在http下使用么

**Comment by yume-chan** [comment]
> 是否是因为非https原因呢？

Yes. See https://github.com/yume-chan/ya-webadb/blob/main/CONTRIBUTING.md#1-webusb-and-file-downloading-doesnt-work-in-developmentself-host-environment
